from __future__ import annotations

from typing import TYPE_CHECKING, Iterable, Iterator, Protocol, runtime_checkable

if TYPE_CHECKING:
    from fflow.common.config import StreamConfig
    from fflow.common.schema import Schema, Stream


@runtime_checkable
class Source(Protocol):
    """Reads data from a source system.

    ``read()`` receives the current state dict for the stream (loaded from the
    state store) and must update it in-place as rows are yielded so that the
    final dict reflects the new watermark.  The pipeline persists the updated
    state only after a successful write + commit for that stream.
    """

    def check(self) -> None:
        """Raise if the source connection/credentials are invalid."""
        ...

    def discover(self) -> "Schema":
        """Return available streams and their column schemas."""
        ...

    def read(self, stream: str, state: dict) -> Iterator[dict]:
        """Yield rows for *stream*, updating *state* in-place as rows flow.

        The caller owns the state dict and will persist it only after the
        destination successfully commits.
        """
        ...


@runtime_checkable
class Destination(Protocol):
    """Writes data to a destination system."""

    def check(self) -> None:
        """Raise if the destination connection/credentials are invalid."""
        ...

    def prepare_stream(
        self,
        stream: str,
        schema: "Stream",
        config: "StreamConfig",
        run_id: str = "",
    ) -> None:
        """Called once per stream before any rows are written.

        ``run_id`` is a UUID4 string generated by the pipeline at the start of
        each run.  Destinations that write to file-based stores (e.g. S3) use
        it for path uniqueness; SQL destinations may ignore it.

        Implementations should create or alter the destination table, stage the
        truncate for ``replace`` disposition, etc.
        """
        ...

    def write(self, stream: str, rows: Iterable[dict]) -> None:
        """Buffer or insert *rows* for *stream*.

        May be called multiple times per stream (once per chunk).  Writes are
        not visible at the destination until ``commit()`` is called.
        """
        ...

    def commit(self, stream: str) -> None:
        """Make buffered writes for *stream* durable.

        Called exactly once per stream, after all rows have been written
        successfully.
        """
        ...

    def rollback(self, stream: str) -> None:
        """Discard buffered writes for *stream* (e.g. on extraction failure).

        Implementations that do not support explicit rollback should implement
        this as a no-op.
        """
        ...


@runtime_checkable
class StateStore(Protocol):
    """Persists incremental cursors between pipeline runs."""

    def get(self, pipeline: str, stream: str) -> dict:
        """Return the current state dict for *(pipeline, stream)*.

        Returns an empty dict if no state exists yet (first run).
        """
        ...

    def set(self, pipeline: str, stream: str, state: dict) -> None:
        """Persist *state* for *(pipeline, stream)*."""
        ...
